using System.Collections.Generic;
using CardsShared;

namespace CardDataLib.CardData.Towers
{
    public static class FrostKeepCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Frost Keep",
                    Description = "Uses mana to slow nearby enemies",
                    SpriteName = "Frost",
                    UnlockName = "FrostKeep",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostHealth1", "FrostArmor1", "FrostShield1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Frostbite I",
                    Description = "All frost keeps deal +1 damage to health",
                    SpriteName = "Frost",
                    UnlockName = "FrostHealth1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostBleed1", "FrostHealth2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Frostbite II",
                    Description = "All frost keeps deal +2 damage to health",
                    SpriteName = "Frost",
                    UnlockName = "FrostHealth2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostStun1", "FrostHealth3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Frostbite III",
                    Description = "All frost keeps deal +3 damage to health",
                    SpriteName = "Frost",
                    UnlockName = "FrostHealth3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostDamage1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Dehydration I",
                    Description = "All frost keeps deal +1 damage to armor",
                    SpriteName = "Frost",
                    UnlockName = "FrostArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostBurn1", "FrostArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Dehydration II",
                    Description = "All frost keeps deal +2 damage to armor",
                    SpriteName = "Frost",
                    UnlockName = "FrostArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "StunDamage1", "FrostArmor3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Dehydration III",
                    Description = "All frost keeps deal +3 damage to armor",
                    SpriteName = "Frost",
                    UnlockName = "FrostArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Conductive Snow I",
                    Description = "All frost keeps deal +1 damage to shields",
                    SpriteName = "Frost",
                    UnlockName = "FrostShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostPoison1", "FrostShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Conductive Snow II",
                    Description = "All frost keeps deal +2 damage to shields",
                    SpriteName = "Frost",
                    UnlockName = "FrostShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostRange1", "FrostShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Conductive Snow III",
                    Description = "All frost keeps deal +3 damage to shields",
                    SpriteName = "Frost",
                    UnlockName = "FrostShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Absolute Zero",
                    Description = "Increase maximum slow percentage by +10%",
                    SpriteName = "Frost",
                    UnlockName = "MaxSlow1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Absolute Zero",
                    Description = "Increase maximum slow percentage by +10%",
                    SpriteName = "Frost",
                    UnlockName = "MaxSlow2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Absolute Zero",
                    Description = "Increase maximum slow percentage by +10%",
                    SpriteName = "Frost",
                    UnlockName = "MaxSlow3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Blizzard I",
                    Description = "All frost keeps gain +1 range",
                    SpriteName = "Frost",
                    UnlockName = "FrostRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostRange2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Blizzard II",
                    Description = "All frost keeps gain +1 range",
                    SpriteName = "Frost",
                    UnlockName = "FrostRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostRange3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Blizzard III",
                    Description = "All frost keeps gain +1 range",
                    SpriteName = "Frost",
                    UnlockName = "FrostRange3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Cooling Rods",
                    Description = "All frost keeps gain +15% crit chance",
                    SpriteName = "Frost",
                    UnlockName = "FrostDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth4", "MaxSlow1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Cooling Rods",
                    Description = "All frost keeps gain +15% crit chance",
                    SpriteName = "Frost",
                    UnlockName = "FrostDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor4", "MaxSlow2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Cooling Rods",
                    Description = "All frost keeps gain +15% crit chance",
                    SpriteName = "Frost",
                    UnlockName = "FrostDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield4", "MaxSlow3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Deep Freeze I",
                    Description = "All frost keeps gain a 10% chance to freeze enemies solid with each hit",
                    SpriteName = "Frost",
                    UnlockName = "FrostStun1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostStun2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Deep Freeze II",
                    Description = "All frost keeps gain +5% chance to freeze enemies solid with each hit",
                    SpriteName = "Frost",
                    UnlockName = "FrostStun2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostStun3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Deep Freeze III",
                    Description = "All frost keeps gain +5% chance to freeze enemies solid with each hit",
                    SpriteName = "Frost",
                    UnlockName = "FrostStun3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Flammable Snow I",
                    Description = "All frost keeps gain 25% burn damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostBurn2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Flammable Snow II",
                    Description = "All frost keeps gain 25% burn damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ice Breaker I",
                    Description = "Frozen enemies take an additional +1 base damage from all damage",
                    SpriteName = "Frost",
                    UnlockName = "StunDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "StunDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ice Breaker II",
                    Description = "Frozen enemies take an additional +1 base damage from all damage",
                    SpriteName = "Frost",
                    UnlockName = "StunDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "StunDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ice Breaker III",
                    Description = "Frozen enemies take an additional +1 base damage from all damage",
                    SpriteName = "Frost",
                    UnlockName = "StunDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Vampiric Snow I",
                    Description = "All frost keeps gain 25% bleed damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostBleed1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FrostBleed2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Vampiric Snow II",
                    Description = "All frost keeps gain 25% bleed damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostBleed2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Yellow Snow I",
                    Description = "All frost keeps gain 25% poison damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FrostPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Yellow Snow II",
                    Description = "All frost keeps gain 25% poison damage",
                    SpriteName = "Frost",
                    UnlockName = "FrostPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Frost",
                    UnlockName = "GlobalHealth4",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Frost",
                    UnlockName = "GlobalArmor4",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Frost",
                    UnlockName = "GlobalShield4",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Snow",
                    Description = "Frost keeps permanently gain +1 damage to health",
                    SpriteName = "Frost",
                    UnlockName = "FrostPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Snow",
                    Description = "Frost keeps permanently gain +1 damage to armor",
                    SpriteName = "Frost",
                    UnlockName = "FrostPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Snow",
                    Description = "Frost keeps permanently gain +1 damage to shield",
                    SpriteName = "Frost",
                    UnlockName = "FrostPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FrostKeep,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
