using System.Collections.Generic;
using CardsShared;

namespace CardDataLib.CardData.Towers
{
    public static class LookoutCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Lookout",
                    Description = "Spots enemies and magnifies the damage they take",
                    SpriteName = "Crosshair",
                    UnlockName = "Lookout",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutHealth1", "LookoutArmor1", "LookoutShield1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Watch I",
                    Description = "All lookouts gain +1 damage to health",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Watch II",
                    Description = "All lookouts gain +2 damage to health",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutHealth3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Watch III",
                    Description = "All lookouts gain +3 damage to health",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutDamage1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Forward Observers I",
                    Description = "All lookouts gain +1 damage to armor",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Forward Observers II",
                    Description = "All lookouts gain +2 damage to armor",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutArmor3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Forward Observers III",
                    Description = "All lookouts gain +3 damage to armor",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "LookoutDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Night Watch I",
                    Description = "All lookouts gain +1 damage to shields",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "LookoutShield2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Night Watch II",
                    Description = "All lookouts gain +2 damage to shields",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "LookoutShield3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Night Watch III",
                    Description = "All lookouts gain +3 damage to shields",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "LookoutDamage3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Binoculars",
                    Description = "All lookouts gain +15% crit chance",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth12" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Binoculars",
                    Description = "All lookouts gain +15% crit chance",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor12" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Binoculars",
                    Description = "All lookouts gain +15% crit chance",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield12" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Crosshair",
                    UnlockName = "GlobalHealth12",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Crosshair",
                    UnlockName = "GlobalArmor12",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Crosshair",
                    UnlockName = "GlobalShield12",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Range Finding",
                    Description = "Lookouts permanently gain +1 damage to health",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Range Finding",
                    Description = "Lookouts permanently gain +1 damage to armor",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Range Finding",
                    Description = "Lookouts permanently gain +1 damage to shield",
                    SpriteName = "Crosshair",
                    UnlockName = "LookoutPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Lookout,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
