using System.Collections.Generic;
using CardsShared;

namespace CardDataLib.CardData.Towers
{
    public static class MortarCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Mortar",
                    Description = "Launch explosive shells over long distances",
                    SpriteName = "Mortar",
                    UnlockName = "Mortar",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarHealth1", "MortarArmor1", "MortarShield1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "HE Shells I",
                    Description = "All mortars gain +1 damage to health",
                    SpriteName = "Mortar",
                    UnlockName = "MortarHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarBleed1", "MortarHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "HE Shells II",
                    Description = "All mortars gain +2 damage to health",
                    SpriteName = "Mortar",
                    UnlockName = "MortarHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarRange1", "MortarHealth3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "HE Shells III",
                    Description = "All mortars gain +3 damage to health",
                    SpriteName = "Mortar",
                    UnlockName = "MortarHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarDamage1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Concussive Shells I",
                    Description = "All mortars gain +1 damage to armor",
                    SpriteName = "Mortar",
                    UnlockName = "MortarArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarBurn1", "MortarArmor2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Concussive Shells II",
                    Description = "All mortars gain +2 damage to armor",
                    SpriteName = "Mortar",
                    UnlockName = "MortarArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarBlast1", "MortarArmor3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Concussive Shells III",
                    Description = "All mortars gain +3 damage to armor",
                    SpriteName = "Mortar",
                    UnlockName = "MortarArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarDamage2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "EMP I",
                    Description = "All mortars gain +1 damage to shields",
                    SpriteName = "Mortar",
                    UnlockName = "MortarShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarPoison1", "MortarShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "EMP II",
                    Description = "All mortars gain +2 damage to shields",
                    SpriteName = "Mortar",
                    UnlockName = "MortarShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarMana1", "MortarShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "EMP III",
                    Description = "All mortars gain +3 damage to shields",
                    SpriteName = "Mortar",
                    UnlockName = "MortarShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Explosives",
                    Description = "All mortars gain +15% crit chance",
                    SpriteName = "Mortar",
                    UnlockName = "MortarDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Explosives",
                    Description = "All mortars gain +15% crit chance",
                    SpriteName = "Mortar",
                    UnlockName = "MortarDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Explosives",
                    Description = "All mortars gain +15% crit chance",
                    SpriteName = "Mortar",
                    UnlockName = "MortarDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Area of Effect I",
                    Description = "All mortars gain 50% blast radius",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBlast1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarBlast2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Area of Effect II",
                    Description = "All mortars gain 50% blast radius",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBlast2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarBlast3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Area of Effect III",
                    Description = "All mortars gain 50% blast radius",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBlast3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Fragmentation I",
                    Description = "All mortars gain 25% bleed damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarBleed2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fragmentation II",
                    Description = "All mortars gain 25% bleed damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Gas Shells I",
                    Description = "All mortars gain 25% poison damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Gas Shells II",
                    Description = "All mortars gain 25% poison damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Incendiary Rounds I",
                    Description = "All mortars gain 25% burn damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBurn1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MortarBurn2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Incendiary Rounds II",
                    Description = "All mortars gain 25% burn damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarBurn2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Long Range Balistics I",
                    Description = "All mortars gain +5 range",
                    SpriteName = "Mortar",
                    UnlockName = "MortarRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarRange2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Long Range Balistics II",
                    Description = "All mortars gain +5 range",
                    SpriteName = "Mortar",
                    UnlockName = "MortarRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bombs I",
                    Description = "Mortars now consume a small amount of mana and gain +4 base damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarMana1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarMana2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bombs II",
                    Description = "Mortars now consume a medium amount of mana and gain +4 base damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarMana2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MortarMana3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bombs III",
                    Description = "Mortars now consume a large amount of mana and gain +4 base damage",
                    SpriteName = "Mortar",
                    UnlockName = "MortarMana3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Mortar",
                    UnlockName = "GlobalHealth2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Mortar",
                    UnlockName = "GlobalArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Mortar",
                    UnlockName = "GlobalShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Bombs",
                    Description = "Mortars permanently gain +1 damage to health",
                    SpriteName = "Mortar",
                    UnlockName = "MortarPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Bombs",
                    Description = "Mortars permanently gain +1 damage to armor",
                    SpriteName = "Mortar",
                    UnlockName = "MortarPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Bombs",
                    Description = "Mortars permanently gain +1 damage to shield",
                    SpriteName = "Mortar",
                    UnlockName = "MortarPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Mortar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
