using System.Collections.Generic;
using CardsShared;

namespace CardDataLib.CardData.Towers
{
    public static class RadarCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Radar",
                    Description = "Call in airstrikes from affar",
                    SpriteName = "Radar",
                    UnlockName = "Radar",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarHealth1", "RadarArmor1", "RadarShield1", "RadarRange1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hollow Point I",
                    Description = "All bi-planes deal +1 damage to health",
                    SpriteName = "Radar",
                    UnlockName = "RadarHealth1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "RadarBleed1", "RadarHealth2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hollow Point II",
                    Description = "All bi-planes deal +2 damage to health",
                    SpriteName = "Radar",
                    UnlockName = "RadarHealth2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "RadarHealth3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hollow Point III",
                    Description = "All bi-planes deal +3 damage to health",
                    SpriteName = "Radar",
                    UnlockName = "RadarHealth3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "RadarDamage1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Full Metal Jacket I",
                    Description = "All bi-planes deal +1 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "RadarArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarBurn1", "RadarArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Full Metal Jacket II",
                    Description = "All bi-planes deal +2 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "RadarArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarArmor3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Full Metal Jacket III",
                    Description = "All bi-planes deal +3 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "RadarArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tracers I",
                    Description = "All bi-planes deal +1 damage to shields",
                    SpriteName = "Radar",
                    UnlockName = "RadarShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarPoison1", "RadarShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tracers II",
                    Description = "All bi-planes deal +2 damage to shields",
                    SpriteName = "Radar",
                    UnlockName = "RadarShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tracers III",
                    Description = "All bi-planes deal +3 damage to shields",
                    SpriteName = "Radar",
                    UnlockName = "RadarShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Frequency Scanning I",
                    Description = "All radars gain +15 range",
                    SpriteName = "Radar",
                    UnlockName = "RadarRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarRange2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Frequency Scanning II",
                    Description = "All radars gain +15 range",
                    SpriteName = "Radar",
                    UnlockName = "RadarRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Incendiary Bullets I",
                    Description = "All bi-planes deal 25% burn damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarBurn2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Incendiary Bullets II",
                    Description = "All bi-planes deal 25% burn damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Mustard Gas I",
                    Description = "All bi-planes deal 25% poison damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "RadarPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Mustard Gas II",
                    Description = "All bi-planes deal 25% poison damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Wounding I",
                    Description = "All bi-planes deal 25% bleed damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarBleed1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "RadarBleed2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Wounding II",
                    Description = "All bi-planes deal 25% bleed damage",
                    SpriteName = "Radar",
                    UnlockName = "RadarBleed2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Better Radios",
                    Description = "All bi-planes gain +15% crit chance",
                    SpriteName = "Radar",
                    UnlockName = "RadarDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth7" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Better Radios",
                    Description = "All bi-planes gain +15% crit chance",
                    SpriteName = "Radar",
                    UnlockName = "RadarDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor7" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Better Radios",
                    Description = "All bi-planes gain +15% crit chance",
                    SpriteName = "Radar",
                    UnlockName = "RadarDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield7" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "GlobalHealth7",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "GlobalArmor7",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "GlobalShield7",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Radar",
                    Description = "Radars permanently gain +1 damage to health",
                    SpriteName = "Radar",
                    UnlockName = "RadarPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Radar",
                    Description = "Radars permanently gain +1 damage to armor",
                    SpriteName = "Radar",
                    UnlockName = "RadarPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Radar",
                    Description = "Radars permanently gain +1 damage to shield",
                    SpriteName = "Radar",
                    UnlockName = "RadarPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Radar,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
