using System.Collections.Generic;
using CardsShared;

namespace CardDataLib.CardData.DOT
{
    public static class DOTBurnCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Kill them with Fire I",
                    Description = "Increase maximum burn/sec by +26 to 50",
                    SpriteName = "Flame",
                    UnlockName = "DOTBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "BurnSpeed", "DOTBurn2", "ExtraBurnDamage1" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Slow Cooker I",
                    Description = "Burning enemies burn faster based on how much slow they have",
                    SpriteName = "Flame",
                    UnlockName = "BurnSpeed",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "BurnSpeed2" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Slow Cooker II",
                    Description = "Increase the rate at which slows affect burn speed",
                    SpriteName = "Flame",
                    UnlockName = "BurnSpeed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "BurnSpeed3" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Slow Cooker III",
                    Description = "Increase the rate at which slows affect burn speed",
                    SpriteName = "Flame",
                    UnlockName = "BurnSpeed3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Kill them with Fire II",
                    Description = "Increase maximum burn/sec by +30 to 80",
                    SpriteName = "Flame",
                    UnlockName = "DOTBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "DOTAll2" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Make them Suffer",
                    Description = "Increase max bleed, burn and poison/sec by +40",
                    SpriteName = "Flame",
                    UnlockName = "DOTAll2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fire and Flames I",
                    Description = "Burning enemies take an extra +1 armor damage from all attacks",
                    SpriteName = "Flame",
                    UnlockName = "ExtraBurnDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "BurnPop1", "ExtraBurnDamage2" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fire and Flames II",
                    Description = "Burning enemies take an extra +1 armor damage from all attacks",
                    SpriteName = "Flame",
                    UnlockName = "ExtraBurnDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ExtraBurnDamage3" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fire and Flames III",
                    Description = "Burning enemies take an extra +1 armor damage from all attacks",
                    SpriteName = "Flame",
                    UnlockName = "ExtraBurnDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ignite I",
                    Description = "Crits deal 10% of the target's current burn as extra burn damage",
                    SpriteName = "Flame",
                    UnlockName = "BurnPop1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "BurnPop2" },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ignite II",
                    Description = "Crits deal an additional 10% of the target's current burn as extra burn damage",
                    SpriteName = "Flame",
                    UnlockName = "BurnPop2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.DOT,
                    Subcategory = Subcategory.DOTBurn,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                }
            });
        }
    }
}
