using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class BallistaCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Ballista",
                    Description = "Fires a bolt every 3 seconds dealing damage to a single enemy",
                    SpriteName = "Ballista",
                    UnlockName = "Ballista",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaHealth1", "BallistaArmor1", "BallistaShield1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Broadhead Bolts I",
                    Description = "All ballistas deal +1 damage to health",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaHealth1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaBleed1", "BallistaHealth2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Broadhead Bolts II",
                    Description = "All ballistas deal +2 damage to health",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaHealth2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaSlow1", "BallistaHealth3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Broadhead Bolts III",
                    Description = "All ballistas deal +3 damage to health",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaHealth3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaDamage1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Heavy Shafts I",
                    Description = "All ballistas deal +1 damage to armor",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaBurn1", "BallistaArmor2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Heavy Shafts II",
                    Description = "All ballistas deal +2 damage to armor",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaRange1", "BallistaArmor3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Heavy Shafts III",
                    Description = "All ballistas deal +3 damage to armor",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaDamage2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Enchanted Bolts I",
                    Description = "All ballistas deal +1 damage to shields",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaPoison1", "BallistaShield2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Enchanted Bolts II",
                    Description = "All ballistas deal +2 damage to shields",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaManaBolts1", "BallistaShield3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Enchanted Bolts III",
                    Description = "All ballistas deal +3 damage to shields",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaDamage3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Frost Bolts I",
                    Description = "All ballistas slow enemies for 5% of the damage they deal",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaSlow1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaSlow2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Frost Bolts II",
                    Description = "All ballistas slow enemies for an additional 5% of the damage they deal",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaSlow2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaFreeze" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Freezing Bolts",
                    Description = "All ballistas gain a 3% chance to freeze enemies",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaFreeze",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Flaming Bolts I",
                    Description = "All ballistas deal 25% burn damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaBurn1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaBurn2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Flaming Bolts II",
                    Description = "All ballistas deal 25% burn damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaBurn2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Balistics",
                    Description = "All ballistas gain +15% crit chance",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaDamage1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalHealth1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Balistics",
                    Description = "All ballistas gain +15% crit chance",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaDamage2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalArmor1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Advanced Balistics",
                    Description = "All ballistas gain +15% crit chance",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaDamage3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalShield1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Jagged Heads I",
                    Description = "All ballistas deal 25% bleed damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaBleed1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaBleed2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Jagged Heads II",
                    Description = "All ballistas deal 25% bleed damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaBleed2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Longbow I",
                    Description = "Double the range bonus elevation gives all ballistas",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaRange1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaRange2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Longbow II",
                    Description = "Triple the range bonus elevation gives all ballistas",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaRange2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaRange3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Longbow III",
                    Description = "Quadruple the range bonus elevation gives all ballistas",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaRange3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bolts I",
                    Description = "Ballistas now consume a small amount of mana and gain +4 base damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaManaBolts1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaManaBolts2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bolts II",
                    Description = "Ballistas now consume a medium amount of mana and gain +4 base damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaManaBolts2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaManaBolts3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Mana Bolts III",
                    Description = "Ballistas now consume a large amount of mana and gain +4 base damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaManaBolts3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Poison Bolts I",
                    Description = "All ballistas deal 25% poison damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaPoison1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "BallistaPoison2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Poison Bolts II",
                    Description = "All ballistas deal 25% poison damage",
                    SpriteName = "Ballista",
                    UnlockName = "BallistaPoison2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Ballista",
                    UnlockName = "GlobalHealth1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Ballista",
                    UnlockName = "GlobalArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Ballista",
                    UnlockName = "GlobalShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.AlwaysInRun,
                },
                new CardDisplayData {
                    Title = "Better Bolts",
                    Description = "Ballistas permanently gain +1 damage to health",
                    SpriteName = "Ballista",
                    UnlockName = "BalistaPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Bolts",
                    Description = "Ballistas permanently gain +1 damage to armor",
                    SpriteName = "Ballista",
                    UnlockName = "BalistaPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Bolts",
                    Description = "Ballistas permanently gain +1 damage to shield",
                    SpriteName = "Ballista",
                    UnlockName = "BalistaPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Ballista,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
