using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class CannonCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Cannon",
                    Description = "Punch holes in enemies with cannon balls",
                    SpriteName = "Cannon",
                    UnlockName = "Cannon",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonHealth1", "CannonArmor1", "CannonShield1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Grape Shot I",
                    Description = "All cannons deal +1 damage to health",
                    SpriteName = "Cannon",
                    UnlockName = "CannonHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonBleed1", "CannonHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Grape Shot II",
                    Description = "All cannons deal +2 damage to health",
                    SpriteName = "Cannon",
                    UnlockName = "CannonHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonRamp1", "CannonHealth3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Grape Shot III",
                    Description = "All cannon deal +3 damage to health",
                    SpriteName = "Cannon",
                    UnlockName = "CannonHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonDamage1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Round Shot I",
                    Description = "All cannons deal +1 damage to armor",
                    SpriteName = "Cannon",
                    UnlockName = "CannonArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "CannonBurn1", "CannonArmor2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Round Shot II",
                    Description = "All cannons deal +2 damage to armor",
                    SpriteName = "Cannon",
                    UnlockName = "CannonArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "CannonSplit1", "CannonArmor3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Round Shot III",
                    Description = "All cannons deal +3 damage to armor",
                    SpriteName = "Cannon",
                    UnlockName = "CannonArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "CannonDamage2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ghosts in Shells I",
                    Description = "All cannons deal +1 damage to shields",
                    SpriteName = "Cannon",
                    UnlockName = "CannonShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonPoison1", "CannonShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ghosts in Shells II",
                    Description = "All cannons deal +2 damage to shields",
                    SpriteName = "Cannon",
                    UnlockName = "CannonShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonRange1", "CannonShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ghosts in Shells III",
                    Description = "All cannons deal +3 damage to shields",
                    SpriteName = "Cannon",
                    UnlockName = "CannonShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Collateral I",
                    Description = "Cannon balls gain +1 damage with every enemy hit",
                    SpriteName = "Cannon",
                    UnlockName = "CannonRamp1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonRamp2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Collateral II",
                    Description = "Cannon balls gain a further +1 damage with every enemy hit",
                    SpriteName = "Cannon",
                    UnlockName = "CannonRamp2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonRamp3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Collateral III",
                    Description = "Cannon balls gain a further +1 damage with every enemy hit",
                    SpriteName = "Cannon",
                    UnlockName = "CannonRamp3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Dismemberment I",
                    Description = "All cannons deal 25% bleed damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonBleed2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Dismemberment II",
                    Description = "All cannons deal 25% bleed damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Gang Green I",
                    Description = "All cannons deal 25% poison damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Gang Green II",
                    Description = "All cannons deal 25% poison damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Math I",
                    Description = "All cannons gain +3 range",
                    SpriteName = "Cannon",
                    UnlockName = "CannonRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "CannonRange2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Math II",
                    Description = "All cannons gain +3 range",
                    SpriteName = "Cannon",
                    UnlockName = "CannonRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Ricochet",
                    Description = "Cannon balls have a chance to split with every hit",
                    SpriteName = "Cannon",
                    UnlockName = "CannonSplit1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Unburnt Powder I",
                    Description = "All cannons deal 25% burn damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonBurn1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "CannonBurn2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Unburnt Powder II",
                    Description = "All cannons deal 25% burn damage",
                    SpriteName = "Cannon",
                    UnlockName = "CannonBurn2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Barrage",
                    Description = "All cannons gain +15% crit chance",
                    SpriteName = "Cannon",
                    UnlockName = "CannonDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth14" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Barrage",
                    Description = "All cannons gain +15% crit chance",
                    SpriteName = "Cannon",
                    UnlockName = "CannonDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor14" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Barrage",
                    Description = "All cannons gain +15% crit chance",
                    SpriteName = "Cannon",
                    UnlockName = "CannonDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield14" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Cannon",
                    UnlockName = "GlobalHealth14",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Cannon",
                    UnlockName = "GlobalArmor14",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Cannon",
                    UnlockName = "GlobalShield14",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Balls",
                    Description = "Cannons permanently gain +1 damage to health",
                    SpriteName = "Cannon",
                    UnlockName = "CannonPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Balls",
                    Description = "Cannons permanently gain +1 damage to armor",
                    SpriteName = "Cannon",
                    UnlockName = "CannonPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Balls",
                    Description = "Cannons permanently gain +1 damage to shield",
                    SpriteName = "Cannon",
                    UnlockName = "CannonPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.Cannon,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
