using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class EncampmentCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Encampment",
                    Description = "Fortifies nearby paths with landmines",
                    SpriteName = "Landmine",
                    UnlockName = "Encampment",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentHealth1", "EncampmentArmor1", "EncampmentShield1", "EncampmentRange1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Barbed Wire I",
                    Description = "All landmines deal +1 damage to health",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentHealth2", "EncampmentBleed1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Barbed Wire II",
                    Description = "All landmines deal +2 damage to health",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentHealth3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Barbed Wire III",
                    Description = "All landmines deal +3 damage to health",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentDamage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Bouncing Betty I",
                    Description = "All landmines deal 25% bleed damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentBleed2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Bouncing Betty II",
                    Description = "All landmines deal 25% bleed damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Concealment",
                    Description = "All landmines gain +15% crit chance",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth11", "MaxHaste1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Concealment",
                    Description = "All landmines gain +15% crit chance",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor11", "MaxHaste2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Concealment",
                    Description = "All landmines gain +15% crit chance",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield11", "MaxHaste3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Fire Storm I",
                    Description = "All landmines deal 25% burn damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentBurn1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "EncampmentBurn2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Fire Storm II",
                    Description = "All landmines deal 25% burn damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentBurn2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "High Explosives I",
                    Description = "All landmines deal +1 damage to armor",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "EncampmentArmor2", "EncampmentBurn1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "High Explosives II",
                    Description = "All landmines deal +2 damage to armor",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "EncampmentArmor3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "High Explosives III",
                    Description = "All landmines deal +3 damage to armor",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "EncampmentDamage2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "No Man's Land I",
                    Description = "All encampments gain +1 range",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentRange2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "No Man's Land II",
                    Description = "All encampments gain +1 range",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentRange3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "No Man's Land III",
                    Description = "All encampments gain +1 range",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentRange3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Proximity Fuses I",
                    Description = "All landmines deal +1 damage to shields",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentShield2", "EncampmentPoison1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Proximity Fuses II",
                    Description = "All landmines deal +2 damage to shields",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentShield3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Proximity Fuses III",
                    Description = "All landmines deal +3 damage to shields",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentDamage3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Punji Sticks I",
                    Description = "All landmines deal 25% poison damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "EncampmentPoison2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Punji Sticks II",
                    Description = "All landmines deal 25% poison damage",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Watch your step!",
                    Description = "Reduce enemies' max haste by -20%",
                    SpriteName = "Landmine",
                    UnlockName = "MaxHaste1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Watch your step!",
                    Description = "Reduce enemies' max haste by -20%",
                    SpriteName = "Landmine",
                    UnlockName = "MaxHaste2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData
                {
                    Title = "Watch your step!",
                    Description = "Reduce enemies' max haste by -20%",
                    SpriteName = "Landmine",
                    UnlockName = "MaxHaste3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Landmine",
                    UnlockName = "GlobalHealth11",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Landmine",
                    UnlockName = "GlobalArmor11",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Landmine",
                    UnlockName = "GlobalShield11",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Better Mines",
                    Description = "Landmines permanently gain +1 damage to health",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Better Mines",
                    Description = "Landmines permanently gain +1 damage to armor",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Encampment",
                },
                new CardDisplayData {
                    Title = "Better Mines",
                    Description = "Landmines permanently gain +1 damage to shield",
                    SpriteName = "Landmine",
                    UnlockName = "EncampmentPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Encampment",
                }
            });
        }
    }
}
