using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class FlameThrowerCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Flame Thrower",
                    Description = "Uses mana to engulf enemies with fire",
                    SpriteName = "Flame",
                    UnlockName = "FlameThrower",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameHealth1", "FlameArmor1", "FlameShield1", "FlameBurn1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Napalm I",
                    Description = "All flame throwers gain +1 damage to health",
                    SpriteName = "Flame",
                    UnlockName = "FlameHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Napalm II",
                    Description = "All flame throwers gain +2 damage to health",
                    SpriteName = "Flame",
                    UnlockName = "FlameHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameHealth3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Napalm III",
                    Description = "All flame throwers gain +3 damage to health",
                    SpriteName = "Flame",
                    UnlockName = "FlameHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameDamage1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Nitric Acid I",
                    Description = "All flame throwers gain +1 damage to armor",
                    SpriteName = "Flame",
                    UnlockName = "FlameArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FlameArmor2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Nitric Acid II",
                    Description = "All flame throwers gain +2 damage to armor",
                    SpriteName = "Flame",
                    UnlockName = "FlameArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FlameArmor3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Nitric Acid III",
                    Description = "All flame throwers gain +3 damage to armor",
                    SpriteName = "Flame",
                    UnlockName = "FlameArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "FlameDamage2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "White Phosphorus I",
                    Description = "All flame throwers gain +1 damage to shields",
                    SpriteName = "Flame",
                    UnlockName = "FlameShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "White Phosphorus II",
                    Description = "All flame throwers gain +2 damage to shields",
                    SpriteName = "Flame",
                    UnlockName = "FlameShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "White Phosphorus III",
                    Description = "All flame throwers gain +3 damage to shields",
                    SpriteName = "Flame",
                    UnlockName = "FlameShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fuel Saturation I",
                    Description = "All flame throwers gain +50% burn",
                    SpriteName = "Flame",
                    UnlockName = "FlameBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameBurn2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fuel Saturation II",
                    Description = "All flame throwers gain +50% burn",
                    SpriteName = "Flame",
                    UnlockName = "FlameBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameBurn3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fuel Saturation III",
                    Description = "All flame throwers gain +50% burn",
                    SpriteName = "Flame",
                    UnlockName = "FlameBurn3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "FlameBurn4" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fuel Saturation IV",
                    Description = "All flame throwers gain +50% burn",
                    SpriteName = "Flame",
                    UnlockName = "FlameBurn4",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Everything Burns",
                    Description = "Increase maximum burn/sec by +100",
                    SpriteName = "Flame",
                    UnlockName = "BurnIncrease1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Everything Burns",
                    Description = "Increase maximum burn/sec by +100",
                    SpriteName = "Flame",
                    UnlockName = "BurnIncrease2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Everything Burns",
                    Description = "Increase maximum burn/sec by +100",
                    SpriteName = "Flame",
                    UnlockName = "BurnIncrease3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pyrochemistry",
                    Description = "All flame throwers gain +15% crit chance",
                    SpriteName = "Flame",
                    UnlockName = "FlameDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth5", "BurnIncrease1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pyrochemistry",
                    Description = "All flame throwers gain +15% crit chance",
                    SpriteName = "Flame",
                    UnlockName = "FlameDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor5", "BurnIncrease2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pyrochemistry",
                    Description = "All flame throwers gain +15% crit chance",
                    SpriteName = "Flame",
                    UnlockName = "FlameDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield5", "BurnIncrease3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Flame",
                    UnlockName = "GlobalHealth5",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Flame",
                    UnlockName = "GlobalArmor5",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Flame",
                    UnlockName = "GlobalShield5",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Fire",
                    Description = "Flame throwers permanently gain +1 damage to health",
                    SpriteName = "Flame",
                    UnlockName = "FlamePHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Fire",
                    Description = "Flame throwers permanently gain +1 damage to armor",
                    SpriteName = "Flame",
                    UnlockName = "FlamePArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Fire",
                    Description = "Flame throwers permanently gain +1 damage to shield",
                    SpriteName = "Flame",
                    UnlockName = "FlamePShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.FlameThrower,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
