using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class MonumentCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Monument",
                    Description = "Uses mana to haunt enemies with spiritual swords",
                    SpriteName = "Monument",
                    UnlockName = "Monument",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentHealth1", "MonumentArmor1", "MonumentsShield1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenge I",
                    Description = "All monuments gain +1 damage to health",
                    SpriteName = "Monument",
                    UnlockName = "MonumentHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentHealth2", "MonumentBleedSpecial1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenge II",
                    Description = "All monuments gain +2 damage to health",
                    SpriteName = "Monument",
                    UnlockName = "MonumentHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentHealth3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenge III",
                    Description = "All monuments gain +3 damage to health",
                    SpriteName = "Monument",
                    UnlockName = "MonumentHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentDamage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Honor I",
                    Description = "All monuments gain +1 damage to armor",
                    SpriteName = "Monument",
                    UnlockName = "MonumentArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentArmor2", "MonumentBurnSpecial1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Honor II",
                    Description = "All monuments gain +2 damage to armor",
                    SpriteName = "Monument",
                    UnlockName = "MonumentArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentArmor3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Honor III",
                    Description = "All monuments gain +3 damage to armor",
                    SpriteName = "Monument",
                    UnlockName = "MonumentArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentDamage2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenant I",
                    Description = "All monuments gain +1 damage to shields",
                    SpriteName = "Monument",
                    UnlockName = "MonumentsShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MonumentsShield2", "MonumentPoisonSpecial1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenant II",
                    Description = "All monuments gain +2 damage to shields",
                    SpriteName = "Monument",
                    UnlockName = "MonumentsShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MonumentsShield3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Revenant III",
                    Description = "All monuments gain +3 damage to shields",
                    SpriteName = "Monument",
                    UnlockName = "MonumentsShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MonumentDamage3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Desecrate I",
                    Description = "All monuments deal +1 damage to poisoned targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentPoisonSpecial1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "MonumentPoisonSpecial2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Desecrate II",
                    Description = "All monuments deal another +1 damage to poisoned targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentPoisonSpecial2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Dismantle I",
                    Description = "All monuments deal +1 damage to burning targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentBurnSpecial1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentBurnSpecial2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Dismantle II",
                    Description = "All monuments deal another +1 damage to burning targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentBurnSpecial2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Martial Prowess",
                    Description = "All monuments gain +15% crit chance",
                    SpriteName = "Monument",
                    UnlockName = "MonumentDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth15" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Martial Prowess",
                    Description = "All monuments gain +15% crit chance",
                    SpriteName = "Monument",
                    UnlockName = "MonumentDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor15" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Martial Prowess",
                    Description = "All monuments gain +15% crit chance",
                    SpriteName = "Monument",
                    UnlockName = "MonumentDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield15" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Slaughter I",
                    Description = "All monuments deal +1 damage to bleeding targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentBleedSpecial1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "MonumentBleedSpecial2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData
                {
                    Title = "Slaughter II",
                    Description = "All monuments deal another +1 damage to bleeding targets",
                    SpriteName = "Monument",
                    UnlockName = "MonumentBleedSpecial2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Monument",
                    UnlockName = "GlobalHealth15",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Monument",
                    UnlockName = "GlobalArmor15",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Monument",
                    UnlockName = "GlobalShield15",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Better Hate",
                    Description = "Monuments permanently gain +1 damage to health",
                    SpriteName = "Monument",
                    UnlockName = "MonumentPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Better Hate",
                    Description = "Monuments permanently gain +1 damage to armor",
                    SpriteName = "Monument",
                    UnlockName = "MonumentPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Monument",
                },
                new CardDisplayData {
                    Title = "Better Hate",
                    Description = "Monuments permanently gain +1 damage to shield",
                    SpriteName = "Monument",
                    UnlockName = "MonumentPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Monument",
                }
            });
        }
    }
}