using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class ObeliskCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Obelisk",
                    Description = "Uses mana to melt nearby enemies",
                    SpriteName = "Obelisk",
                    UnlockName = "Obelisk",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskHealth1", "ObeliskArmor1", "ObeliskShield1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Disintegration I",
                    Description = "All obelisks deal +1 damage to health",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskHealth2", "ObeliskBleed1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Disintegration II",
                    Description = "All obelisks deal +2 damage to health",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskHealth3", "ObeliskManaUsage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Disintegration III",
                    Description = "All obelisks deal +3 damage to health",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskDamage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Thermal Detonation I",
                    Description = "All obelisks deal +1 damage to armor",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskArmor1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ObeliskArmor2", "ObeliskBurn1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Thermal Detonation II",
                    Description = "All obelisks deal +2 damage to armor",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskArmor2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ObeliskArmor3", "ObeliskTimeOnTarget1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Thermal Detonation III",
                    Description = "All obelisks deal +3 damage to armor",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskArmor3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ObeliskDamage2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Anti-Magic Ray I",
                    Description = "All obelisks deal +1 damage to shields",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskShield2", "ObeliskPoison1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Anti-Magic Ray II",
                    Description = "All obelisks deal +2 damage to shields",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskShield3", "ObeliskRange1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Anti-Magic Ray III",
                    Description = "All obelisks deal +3 damage to shields",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskDamage3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Death Ray I",
                    Description = "All obelisks deal 25% bleed damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskBleed2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Death Ray II",
                    Description = "All obelisks deal 25% bleed damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Disease Ray I",
                    Description = "All obelisks deal 25% poison damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskPoison2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Disease Ray II",
                    Description = "All obelisks deal 25% poison damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Focus Fire",
                    Description = "Obelisks deal +1 base damage for every second they target the same enemy",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskTimeOnTarget1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Immolation I",
                    Description = "All obelisks deal 25% burn damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskBurn1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ObeliskBurn2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Immolation II",
                    Description = "All obelisks deal 25% burn damage",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskBurn2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Mana Cycling I",
                    Description = "Reduce the mana cost of all obelisks by 20%",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskManaUsage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskManaUsage2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Mana Cycling II",
                    Description = "Reduce the mana cost of all obelisks by 20%",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskManaUsage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskManaUsage3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Mana Cycling III",
                    Description = "Reduce the mana cost of all obelisks by 20%",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskManaUsage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Power Projection I",
                    Description = "All obelisks gain +1 range",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskRange2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Power Projection II",
                    Description = "All obelisks gain +1 range",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ObeliskRange3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Power Projection III",
                    Description = "All obelisks gain +1 range",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskRange3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Destruction",
                    Description = "All obelisks gain +15% crit chance",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskDamage1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalHealth8" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Destruction",
                    Description = "All obelisks gain +15% crit chance",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskDamage2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalArmor8" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData
                {
                    Title = "Destruction",
                    Description = "All obelisks gain +15% crit chance",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskDamage3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalShield8" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to health",
                    SpriteName = "Obelisk",
                    UnlockName = "GlobalHealth8",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Obelisk",
                    UnlockName = "GlobalArmor8",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to shields",
                    SpriteName = "Obelisk",
                    UnlockName = "GlobalShield8",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Better Lasers",
                    Description = "Obelisks permanently gain +1 damage to health",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Better Lasers",
                    Description = "Obelisks permanently gain +1 damage to armor",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Obelisk",
                },
                new CardDisplayData {
                    Title = "Better Lasers",
                    Description = "Obelisks permanently gain +1 damage to shield",
                    SpriteName = "Obelisk",
                    UnlockName = "ObeliskPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "Obelisk",
                }
            });
        }
    }
}
