using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class ParticleCannonCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Particle Cannon",
                    Description = "Uses mana to obliterate enemies at long ranges",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannon",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonHealth1", "ParticleCannonArmor1", "ParticleCannonShield1", "ParticleCannonRange1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Excitation I",
                    Description = "All particle cannons deal +1 damage to health",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonHealth2", "ParticleCannonBleed1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Excitation II",
                    Description = "All particle cannons deal +2 damage to health",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonHealth3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Excitation III",
                    Description = "All particle cannons deal +3 damage to health",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonDamage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Heavy Particles I",
                    Description = "All particle cannons deal +1 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonArmor2", "ParticleCannonBurn1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Heavy Particles II",
                    Description = "All particle cannons deal +2 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonArmor3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Heavy Particles III",
                    Description = "All particle cannons deal +3 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonDamage2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Antimatter I",
                    Description = "All particle cannons deal +1 damage to shields",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ParticleCannonShield2", "ParticleCannonPoison1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Antimatter II",
                    Description = "All particle cannons deal +2 damage to shields",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ParticleCannonShield3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Antimatter III",
                    Description = "All particle cannons deal +3 damage to shields",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ParticleCannonDamage3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Attenuation I",
                    Description = "All particle cannons gain +10 range",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonRange2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Attenuation II",
                    Description = "All particle cannons gain +10 range",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Electron Scattering I",
                    Description = "All particle cannons deal 25% bleed damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonBleed2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Electron Scattering II",
                    Description = "All particle cannons deal 25% bleed damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Gamma Rays I",
                    Description = "All particle cannons deal 25% poison damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonPoison1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "ParticleCannonPoison2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Gamma Rays II",
                    Description = "All particle cannons deal 25% poison damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonPoison2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Superheating I",
                    Description = "All particle cannons deal 25% burn damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "ParticleCannonBurn2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Superheating II",
                    Description = "All particle cannons deal 25% burn damage",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Quantum Physics",
                    Description = "All particle cannons gain +15% crit chance",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth9" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Quantum Physics",
                    Description = "All particle cannons gain +15% crit chance",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor9" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Quantum Physics",
                    Description = "All particle cannons gain +15% crit chance",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield9" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "GlobalHealth9",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "GlobalArmor9",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "GlobalShield9",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData {
                    Title = "Better Particles",
                    Description = "Particle cannons permanently gain +1 damage to health",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData {
                    Title = "Better Particles",
                    Description = "Particle cannons permanently gain +1 damage to armor",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                },
                new CardDisplayData {
                    Title = "Better Particles",
                    Description = "Particle cannons permanently gain +1 damage to shield",
                    SpriteName = "ParticleCannon",
                    UnlockName = "ParticleCannonPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "ParticleCannon",
                }
            });
        }
    }
}
