using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class PoisonSprayerCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Poison Sprayer",
                    Description = "Uses mana to spray enemies with poison",
                    SpriteName = "Poison",
                    UnlockName = "PoisonSprayer",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonHealth1", "PoisonArmor1", "PoisonShield1", "PoisonPoison1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Infection I",
                    Description = "All poison sprayers gain +1 damage to health",
                    SpriteName = "Poison",
                    UnlockName = "PoisonHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonHealth2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Infection II",
                    Description = "All poison sprayers gain +2 damage to health",
                    SpriteName = "Poison",
                    UnlockName = "PoisonHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonHealth3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Infection III",
                    Description = "All poison sprayers gain +3 damage to health",
                    SpriteName = "Poison",
                    UnlockName = "PoisonHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonDamage1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Corrosion I",
                    Description = "All poison sprayers gain +1 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "PoisonArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Corrosion II",
                    Description = "All poison sprayers gain +2 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "PoisonArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonArmor3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Corrosion III",
                    Description = "All poison sprayers gain +3 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "PoisonArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fumigation I",
                    Description = "All poison sprayers gain +1 damage to shields",
                    SpriteName = "Poison",
                    UnlockName = "PoisonShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "PoisonShield2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fumigation II",
                    Description = "All poison sprayers gain +2 damage to shields",
                    SpriteName = "Poison",
                    UnlockName = "PoisonShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "PoisonShield3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Fumigation III",
                    Description = "All poison sprayers gain +3 damage to shields",
                    SpriteName = "Poison",
                    UnlockName = "PoisonShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "PoisonDamage3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Spores I",
                    Description = "All poison sprayers gain +50% poison damage",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Spores II",
                    Description = "All poison sprayers gain +50% poison damage",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonPoison3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Spores III",
                    Description = "All poison sprayers gain +50% poison damage",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPoison3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "PoisonPoison4" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Spores IV",
                    Description = "All poison sprayers gain +50% poison damage",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPoison4",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pandemic",
                    Description = "Increase maximum poison/sec by +100",
                    SpriteName = "Poison",
                    UnlockName = "PoisonIncrease1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pandemic",
                    Description = "Increase maximum poison/sec by +100",
                    SpriteName = "Poison",
                    UnlockName = "PoisonIncrease2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Pandemic",
                    Description = "Increase maximum poison/sec by +100",
                    SpriteName = "Poison",
                    UnlockName = "PoisonIncrease3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Biochemistry",
                    Description = "All poison sprayers gain +15% crit chance",
                    SpriteName = "Poison",
                    UnlockName = "PoisonDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth6", "PoisonIncrease1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Biochemistry",
                    Description = "All poison sprayers gain +15% crit chance",
                    SpriteName = "Poison",
                    UnlockName = "PoisonDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor6", "PoisonIncrease2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Biochemistry",
                    Description = "All poison sprayers gain +15% crit chance",
                    SpriteName = "Poison",
                    UnlockName = "PoisonDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield6", "PoisonIncrease3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "GlobalHealth6",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "GlobalArmor6",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "GlobalShield6",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Poison",
                    Description = "Poison sprayers permanently gain +1 damage to health",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Poison",
                    Description = "Poison sprayers permanently gain +1 damage to armor",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Poison",
                    Description = "Poison sprayers permanently gain +1 damage to shield",
                    SpriteName = "Poison",
                    UnlockName = "PoisonPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.PoisonSprayer,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
