using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class TeslaCoilCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData {
                    Title = "Tesla Coil",
                    Description = "Uses mana to electrify nearby enemies",
                    SpriteName = "TeslaCoil",
                    UnlockName = "",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "TeslaHealth1", "TeslaArmor1", "TeslaShield1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Power Surge I",
                    Description = "All tesla coils gain +1 damage to health",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaHealth1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaHealth2", "TeslaBleed1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Power Surge II",
                    Description = "All tesla coils gain +2 damage to health",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaHealth2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaHealth3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Power Surge III",
                    Description = "All tesla coils gain +3 damage to health",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaDamage1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Plasmatics I",
                    Description = "All tesla coils gain +1 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaArmor2", "TeslaBurn1" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Plasmatics II",
                    Description = "All tesla coils gain +2 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaArmor3" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Plasmatics III",
                    Description = "All tesla coils gain +3 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaDamage2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Static Permeation I",
                    Description = "All tesla coils gain +1 damage to shields",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaShield1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "TeslaShield2", "TeslaPoison1" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Static Permeation II",
                    Description = "All tesla coils gain +2 damage to shields",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaShield2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "TeslaShield3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Static Permeation III",
                    Description = "All tesla coils gain +3 damage to shields",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaShield3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "TeslaDamage3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Electro Hemorrhaging I",
                    Description = "All tesla coils gain 25% bleed damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaBleed1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaBleed2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Electro Hemorrhaging II",
                    Description = "All tesla coils gain 25% bleed damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaBleed2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Electrogenesis I",
                    Description = "All tesla coils gain 25% poison damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaPoison1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "TeslaPoison2" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Electrogenesis II",
                    Description = "All tesla coils gain 25% poison damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaPoison2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> {  },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Thermal Arcing I",
                    Description = "All tesla coils gain 25% burn damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "TeslaBurn2" },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Thermal Arcing II",
                    Description = "All tesla coils gain 25% burn damage",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Advanced Circuits",
                    Description = "All tesla coils gain +15% crit chance",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaDamage1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalHealth3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Advanced Circuits",
                    Description = "All tesla coils gain +15% crit chance",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaDamage2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalArmor3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Advanced Circuits",
                    Description = "All tesla coils gain +15% crit chance",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaDamage3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "GlobalShield3" },
                    Unlocked = true,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "GlobalHealth3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "GlobalArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreUnlocksInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "GlobalShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.AlwaysInRun,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Better Electricity",
                    Description = "Tesla coils permanently gain +1 damage to health",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Better Electricity",
                    Description = "Tesla coils permanently gain +1 damage to armor",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                },
                new CardDisplayData {
                    Title = "Better Electricity",
                    Description = "Tesla coils permanently gain +1 damage to shield",
                    SpriteName = "TeslaCoil",
                    UnlockName = "TeslaPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = CardCategory.Tower,
                    AcquisitionType = CardAcquisitionType.StoreAppliesPermanent,
                    AssociatedTowerOrBuilding = "TeslaCoil",
                }
            });
        }
    }
}
