using System.Collections.Generic;
using CardsShared;

namespace AllCardsLib.CardData.Towers
{
    public static class VampireLairCards
    {
        internal static void Register()
        {
            Plugin.CardDisplayDataCollection.AllCards.AddRange(new List<CardDisplayData>
            {
                new CardDisplayData
                {
                    Title = "Vampire Lair",
                    Description = "Uses mana to drain life from enemies in a large area",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLair",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairHealth1", "VampireLairArmor1", "VampireLairShield1", "VampireLairRange1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Dark Night I",
                    Description = "All vampire lairs deal +1 damage to health",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealth1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "VampireLairBleed1", "VampireLairHealth2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Dark Night II",
                    Description = "All vampire lairs deal +2 damage to health",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealth2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "VampireLairHealth3" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Dark Night III",
                    Description = "All vampire lairs deal +3 damage to health",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealth3",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "VampireLairDamage1" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Toccata and Fugue I",
                    Description = "All vampire lairs deal +1 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairArmor1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairBurn1", "VampireLairArmor2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Toccata and Fugue II",
                    Description = "All vampire lairs deal +2 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairArmor2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairArmor3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Toccata and Fugue III",
                    Description = "All vampire lairs deal +3 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairArmor3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairDamage2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Supernatural Smell I",
                    Description = "All vampire lairs deal +1 damage to shields",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairShield1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairPoison1", "VampireLairShield2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Supernatural Smell II",
                    Description = "All vampire lairs deal +2 damage to shields",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairShield2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairShield3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Supernatural Smell III",
                    Description = "All vampire lairs deal +3 damage to shields",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairShield3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairDamage3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hunting Grounds I",
                    Description = "All vampire lairs gain +3 range",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairRange1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairRange2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hunting Grounds II",
                    Description = "All vampire lairs gain +3 range",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairRange2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairRange3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Hunting Grounds III",
                    Description = "All vampire lairs gain +3 range",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairRange3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Bald Mountain I",
                    Description = "All vampire lairs deal 25% burn damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairBurn1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairBurn2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Bald Mountain II",
                    Description = "All vampire lairs deal 25% burn damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairBurn2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Feast I",
                    Description = "All vampire lairs deal 25% bleed damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairBleed1",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { "VampireLairBleed2" },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Feast II",
                    Description = "All vampire lairs deal 25% bleed damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairBleed2",
                    UnlockedByDefault = true,
                    Unlocks = new List<string> { },
                    Unlocked = true,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Vampiric Curse I",
                    Description = "All vampire lairs deal 25% poison damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairPoison1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "VampireLairPoison2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Vampiric Curse II",
                    Description = "All vampire lairs deal 25% poison damage",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairPoison2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tower of Blood",
                    Description = "Every round vampire lairs have a +6% chance to heal the main tower",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealing1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tower of Blood",
                    Description = "Every round vampire lairs have a +6% chance to heal the main tower",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealing2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Tower of Blood",
                    Description = "Every round vampire lairs have a +6% chance to heal the main tower",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairHealing3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Gothic Horror",
                    Description = "All vampire lairs gain +15% crit chance",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairDamage1",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalHealth13", "VampireLairHealing1" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Gothic Horror",
                    Description = "All vampire lairs gain +15% crit chance",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairDamage2",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalArmor13", "VampireLairHealing2" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Gothic Horror",
                    Description = "All vampire lairs gain +15% crit chance",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairDamage3",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { "GlobalShield13", "VampireLairHealing3" },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "GlobalHealth13",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "GlobalArmor13",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData
                {
                    Title = "Monster Studies",
                    Description = "All towers gain +1 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "GlobalShield13",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> { },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreUnlocksInRun,
                },
                new CardDisplayData {
                    Title = "Better Vampires",
                    Description = "Vampire lairs permanently gain +1 damage to health",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairPHealth",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Vampires",
                    Description = "Vampire lairs permanently gain +1 damage to armor",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairPArmor",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                },
                new CardDisplayData {
                    Title = "Better Vampires",
                    Description = "Vampire lairs permanently gain +1 damage to shield",
                    SpriteName = "VampireLair",
                    UnlockName = "VampireLairPShield",
                    UnlockedByDefault = false,
                    Unlocks = new List<string> {  },
                    Unlocked = false,
                    Category = Category.Tower,
                    Subcategory = Subcategory.VampireLair,
                    AcquisitionType = AcquisitionType.StoreAppliesPermanent,
                }
            });
        }
    }
}
